version: "3.4"
services:
 vite_docker:
   image: node:alpine
   container_name: vite_docker
   entrypoint: /bin/sh
   build:
     context: ./
     dockerfile: Dockerfile
   restart: always
   command: npm run dev
   ports:
     - 8000:8000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true
 nginx:
  image: nginx:1.13 # this will use the latest version of 1.13.x
  ports:
    - '80:80' # expose 80 on host and sent to 80 in container
  depends_on:
    - vite_docker
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro